# Generated by Django 3.2.5 on 2021-07-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruid', models.IntegerField()),
                ('prname', models.CharField(max_length=200)),
                ('prnameFR', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('update', models.IntegerField(blank=True)),
                ('numconf', models.BigIntegerField()),
                ('numprob', models.BigIntegerField()),
                ('numdeaths', models.BigIntegerField()),
                ('numtotal', models.BigIntegerField()),
                ('numtested', models.BigIntegerField(blank=True)),
                ('numrecover', models.BigIntegerField(blank=True)),
                ('percentrecover', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('ratetested', models.BigIntegerField(blank=True)),
                ('numtoday', models.BigIntegerField()),
                ('percentoday', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ratetotal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ratedeaths', models.DecimalField(decimal_places=2, max_digits=19)),
                ('numdeathstoday', models.BigIntegerField()),
                ('percentdeath', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numtestedtoday', models.BigIntegerField(blank=True)),
                ('numrecoveredtoday', models.BigIntegerField(blank=True)),
                ('percentactive', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numactive', models.BigIntegerField()),
                ('rateactive', models.DecimalField(decimal_places=2, max_digits=19)),
                ('numtotal_last14', models.BigIntegerField(blank=True)),
                ('ratetotal_last14', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('numdeaths_last14', models.BigIntegerField(blank=True)),
                ('ratedeaths_last14', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('numtotal_last7', models.BigIntegerField(blank=True)),
                ('ratetotal_last7', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('numdeaths_last7', models.BigIntegerField(blank=True)),
                ('ratedeaths_last7', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('avgtotal_last7', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('avgincidence_last7', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('avgdeaths_last7', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('avgratedeaths_last7', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
            ],
        ),
    ]
