# Generated by Django 3.2.5 on 2021-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20210719_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record1',
            name='numconf',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numdeaths',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numprob',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numrecover',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numtested',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numtoday',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='record1',
            name='prname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record1',
            name='prnameFR',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record1',
            name='pruid',
            field=models.IntegerField(),
        ),
    ]
