# Generated by Django 3.2.5 on 2021-07-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20210719_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record1',
            name='numtested',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
