# Generated by Django 3.2.5 on 2021-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_auto_20210719_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record1',
            name='avgdeaths_last7',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='avgincidence_last7',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='avgratedeaths_last7',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='avgtotal_last7',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='numdeaths_last14',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='numdeaths_last7',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='numrecover',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='numrecoveredtoday',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='numtested',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numtestedtoday',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='numtotal_last14',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='numtotal_last7',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='percentrecover',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='ratedeaths_last14',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='ratedeaths_last7',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='ratetested',
            field=models.BigIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='ratetotal_last14',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='ratetotal_last7',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record1',
            name='update',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
