# Generated by Django 3.2.5 on 2021-07-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_alter_record1_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record1',
            name='numtested',
            field=models.BigIntegerField(null=True),
        ),
    ]
