# Generated by Django 3.2.5 on 2021-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_record1_avgratedeaths_last7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record1',
            name='avgratedeaths_last7',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
