# Generated by Django 3.2.5 on 2021-08-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_auto_20210804_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
