# Generated by Django 3.2.5 on 2021-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_emailsubscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record1',
            name='numconf',
            field=models.CharField(blank=True, max_length=255, verbose_name='number_of_confirmed'),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numdeaths',
            field=models.CharField(blank=True, max_length=255, verbose_name='number_of_deaths'),
        ),
        migrations.AlterField(
            model_name='record1',
            name='numtotal',
            field=models.CharField(blank=True, max_length=255, verbose_name='Total_number_of_cases'),
        ),
        migrations.AlterField(
            model_name='record1',
            name='prname',
            field=models.CharField(max_length=200, verbose_name='Province_Name'),
        ),
        migrations.AlterField(
            model_name='record1',
            name='pruid',
            field=models.IntegerField(verbose_name='Province_Id'),
        ),
    ]
