# Generated by Django 3.2.5 on 2021-08-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_auto_20210806_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailSubscriber',
        ),
    ]
