# Generated by Django 3.2.5 on 2021-08-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
